<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-GKI4CMR" failures="1" tests="1" name="Default test" time="0.106" errors="0" timestamp="2025-06-03T18:40:18 IST">
  <testcase classname="Selenium.TestOne.PracticeOne" name="ActionsInSellProducts" time="0.029">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.openqa.selenium.WebDriver.findElement(org.openqa.selenium.By)&amp;quot; because &amp;quot;driver&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.findElement(org.openqa.selenium.By)" because "driver" is null
at Selenium.TestOne.BaseClass.NavigateToSellProducts(BaseClass.java:350)
at Selenium.TestOne.PracticeOne.ActionsInSellProducts(PracticeOne.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- ActionsInSellProducts -->
  <testcase classname="Selenium.TestOne.PracticeOne" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
  <testcase classname="Selenium.TestOne.PracticeOne" name="EnterPartsInTheInward" time="0.0">
    <ignored/>
  </testcase> <!-- EnterPartsInTheInward -->
  <testcase classname="Selenium.TestOne.PracticeOne" name="inwardCheckAfterCreatingTheInvoice" time="0.0">
    <ignored/>
  </testcase> <!-- inwardCheckAfterCreatingTheInvoice -->
  <testcase classname="Selenium.TestOne.PracticeOne" name="OnlyCreditNote" time="0.0">
    <ignored/>
  </testcase> <!-- OnlyCreditNote -->
  <testcase classname="Selenium.TestOne.PracticeOne" name="CancelInvoiceVisible" time="0.0">
    <ignored/>
  </testcase> <!-- CancelInvoiceVisible -->
  <testcase classname="Selenium.TestOne.PracticeOne" name="IssueTheCreditNote" time="0.0">
    <ignored/>
  </testcase> <!-- IssueTheCreditNote -->
</testsuite> <!-- Default test -->
